# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValidateEarlGrey' do
  pod 'EarlGreyApp', '2.0.0-rc'
end

target 'ValidateEarlGreyUITests' do
  pod 'EarlGreyTest', '2.0.0-rc'
end
